Update patch set 1
Patch Set 1: Verified+1 Code-Review+1

Comments by kdrag0n - The fix for the undefined reference to 'stpcpy' error has been finalized in upstream, so updating to the new fix (and reverting the old one if you have it) is recommended

Patch-set: 1
Reviewer: Gerrit User 1000495 <1000495@3162e3d8-d894-470e-abd9-724f7b0effad>
Reviewer: Gerrit User 1000598 <1000598@3162e3d8-d894-470e-abd9-724f7b0effad>
Label: Code-Review=+1
Label: Verified=+1